
name: Integración Continua
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-lastest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalar dependencias
        run: npm install
      - name: Instalar Jest globalmente
        run: npm install -g jest
      - name: Verificar instalación de Jest
        run: npx jest --version
      - name: Ejecutar pruebas
        run: npm test